# Generated by Django 3.2 on 2022-03-13 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(verbose_name='is answer correct'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=200, verbose_name='question answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=400, verbose_name='question text'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='is test deleted'),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=100, verbose_name='test name'),
        ),
        migrations.AlterField(
            model_name='test',
            name='publish_date',
            field=models.DateField(auto_now_add=True, verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='test',
            name='question_number',
            field=models.PositiveIntegerField(verbose_name='question number'),
        ),
        migrations.CreateModel(
            name='TestPassing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_date', models.DateField(auto_now_add=True, verbose_name='passing date')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_by_users', to='core.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.BigIntegerField(verbose_name='user answer id')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_by_users', to='core.question')),
                ('test_passing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='core.testpassing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
